#服务端口号
server:
  port: 9100
spring:
    application:
        name: app-eureka-server
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
#     注册地址
#defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 单机版
     defaultZone: http://${eureka.instance.hostname}:8100/eureka/
#     因为自己是注册中心，是需要将自己注册给自己的注册中心（集群的时候是需要为true）
#register-with-eureka: false 单机版
    register-with-eureka: true
#    因为自己是注册中心，不需要检索
#    fetch-registry: false
    fetch-registry: true