
###服务注册地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka,http://localhost:9100/eureka
###api网关端口号      
server:
  port: 82
###网关名称  
spring:
  application:
    name: service-zuul
  cloud:
    config:
    ####读取后缀
      profile: dev
      ####读取config-server注册地址
      discovery:
        service-id: config-server
        enabled: true    
zuul:
  routes:
  ###定义转发服务规则
    api-a:
    ### 当客户端发送请求 127.0.0.1:80/api-member开头的 都会转发到会员服务
      path: /api-member/**
      ###服务别名  zuul网关默认整合ribbon 自动实现负载均衡轮训效果
      serviceId: app-itmayiedu-member
    api-b:
     ### 当客户端发送请求 127.0.0.1:80/api-order开头的 都会转发到订单服务
      path: /api-order/**
      ##订单服务别名
      serviceId: app-itmayiedu-order
    api-c:
     ### 当客户端发送请求 127.0.0.1:80/api-pay开头的 都会转发到支付服务
      path: /api-pay/**
      ##订单服务别名
      serviceId: app-itmayiedu-pay
###默认服务读取eureka注册服务列表 默认间隔30秒

###开启所有监控中心接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
